### ISSUE TITLE
Cloudfront/s3 is dropping query params

### ISSUE THREAD

**Issue by devinmatte** [transitmatters/t-performance-dash#750]
**Describe the bug**
When visiting https://dashboard-beta.labs.transitmatters.org/rapidtransit?config=Orange,70030,70022,2023-07-09,2023-07-11 it’s supposed to redirect to the correct page equivalent. Locally it does, totally fine. Both on the nextjs server and when served the generated bundle
But in s3, it seems to strip away the query params

**To Reproduce**
https://dashboard-beta.labs.transitmatters.org/rapidtransit?config=Orange,70030,70022,2023-07-09,2023-07-11 will 302 to https://dashboard-beta.labs.transitmatters.org/rapidtransit and stay there

**Expected behavior**

- https://dashboard-beta.labs.transitmatters.org/rapidtransit?config=Orange,70030,70022,2023-07-09,2023-07-11

should result in

- https://dashboard-beta.labs.transitmatters.org/orange/trips/multi/?from=70030&to=70022&startDate=2023-07-09&endDate=2023-07-11

**Additional context**

https://stackoverflow.com/questions/30775068/amazon-s3-redirect-rule-preserve-query-params/30798325#30798325

**Comment by mathcolo** [comment]
@devinmatte so here's the scoop...here's what's happening

S3 is responding to `/rapidtransit` with a 302 because `/rapidtransit` doesn't actually exist in v4... `rapidtransit` is a directory (or in the S3 world, a prefix), not an actual page. So you'll notice that if you go to the URL with a trailing slash in the middle, it'll work:
```
                                                       ⬇                 
```
https://dashboard-v4-beta.labs.transitmatters.org/rapidtransit/?config=Orange,70030,70022,2023-07-09,2023-07-11

So just to emphasize, S3 is what's doing that bad 302, not nextjs. What to do about it?

In https://github.com/transitmatters/t-performance-dash/pull/367 @PatrickCleary added `trailingSlash: true` to the next config, which is causing the output static build to have the following structure:

```
prestonmueller@Preston14 ~ $ AWS_PROFILE=transitmatters aws s3 ls s3://dashboard-v4-beta.labs.transitmatters.org/rapidtransit/
2023-07-13 17:18:47       1947 index.html
```

_To fix this particular issue_, there needs to be a file at the path `rapidtransit` with no `.html` extension, [with the right Content-type set](https://stackoverflow.com/a/27046083).

Why did this not happen in V3? V3 was set up for the backend to set EVERY frontend request to `/index.html`, and React dealt with whether or not the path was legit (so the HTTP request always returned 200 no matter what).

What we're doing now is definitely better, we just might have to duct tape a bit to make that old route work. I see two choices:

1. Even though @PatrickCleary explicitly added `trailingSlash:true`, we could try with it off and see what happens.
2. We can separate the v3 to v4 handler code from nextjs and throw a `rapidtransit` html file upload into the deploy script that handles that with `trailingSlash` remaining on.

**Comment by devinmatte** [comment]
So this is interesting. So `/rapidtransit` is not the only route where this happens. All v3 translations (`/rapidtransit`, `/bus` and `/slowzones`)

There's also a case where clicking on the slow zone on the line segment graph has a similar situation where the query params are squashed, I figured they may be related. But given your explanation, it might not be (I'll do some testing)

**Comment by devinmatte** [comment]
@mathcolo So we need to create 3 files. What exactly do these files need to be? Copies of the existing ones?

**Comment by mathcolo** [comment]
it works @devinmatte! we gucci
