### ISSUE TITLE
Multi-day bus trips have different date range options than subway

### ISSUE THREAD

**Issue by rudiejd** [transitmatters/t-performance-dash#916]
**Describe the bug**

**To Reproduce**
1. Go to multi-day subway trips
2. Click on date selection and observe options
3. Go to multi-day bus trips
4. Click on date selection and observe the options are different 

**Expected behavior**

I think the options should be consistent for better usability

**Screenshots**

**Device Info (please complete the following information):**
 - Device: [e.g. iPhone 6, Laptop]
 - OS: [e.g. iOS, Windows]
 - Browser: [e.g. Chrome, Safari]
 - Browser Version: [e.g. 22]

**Additional context**

**Comment by devinmatte** [comment]
This is expected. Bus data isn't live. We only get bus data in monthly batches about 2 months after the month ends. Because of that, we need to have a different set of date options.
Once https://github.com/transitmatters/gobble is up and running, then we'll be able to have them share the date selectors

**Comment by rudiejd** [comment]
@devinmatte  ahhh gotcha, forgot about that! maybe a disclaimer in the meantime about why the date ranges are different? I only see this generic one on the page 
![image](https://github.com/transitmatters/t-performance-dash/assets/46619169/624f04a0-5678-41c4-8c6d-2a575a25d8f4)
